//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/4Hands2Cats/VideoPlayer/Scripts/VideoPlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/4Hands2Cats/VideoPlayer/Scripts/VideoPlayerInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @VideoPlayerInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @VideoPlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""VideoPlayerInputs"",
    ""maps"": [
        {
            ""name"": ""VideoPlayerControl"",
            ""id"": ""a22a48bf-a40b-4188-ac90-6f2a3498cd80"",
            ""actions"": [
                {
                    ""name"": ""PlayPause"",
                    ""type"": ""Button"",
                    ""id"": ""bf6194d1-d790-40dd-9699-58b0778a4799"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextFrame"",
                    ""type"": ""Button"",
                    ""id"": ""7afbc1fb-fa4f-4032-a2b9-9485ad21eb28"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousFrame"",
                    ""type"": ""Button"",
                    ""id"": ""9c48ba60-a00c-49a6-acfa-de141ad8c587"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2d7b828-0e91-4ef7-9308-db4e970b7cd5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a73852a4-224e-43a2-96fa-742190316134"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextFrame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed2a7e0b-5e6e-436d-973e-f8773242ecfa"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousFrame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VideoPlayerControl
        m_VideoPlayerControl = asset.FindActionMap("VideoPlayerControl", throwIfNotFound: true);
        m_VideoPlayerControl_PlayPause = m_VideoPlayerControl.FindAction("PlayPause", throwIfNotFound: true);
        m_VideoPlayerControl_NextFrame = m_VideoPlayerControl.FindAction("NextFrame", throwIfNotFound: true);
        m_VideoPlayerControl_PreviousFrame = m_VideoPlayerControl.FindAction("PreviousFrame", throwIfNotFound: true);
    }

    ~@VideoPlayerInputs()
    {
        UnityEngine.Debug.Assert(!m_VideoPlayerControl.enabled, "This will cause a leak and performance issues, VideoPlayerInputs.VideoPlayerControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VideoPlayerControl
    private readonly InputActionMap m_VideoPlayerControl;
    private List<IVideoPlayerControlActions> m_VideoPlayerControlActionsCallbackInterfaces = new List<IVideoPlayerControlActions>();
    private readonly InputAction m_VideoPlayerControl_PlayPause;
    private readonly InputAction m_VideoPlayerControl_NextFrame;
    private readonly InputAction m_VideoPlayerControl_PreviousFrame;
    /// <summary>
    /// Provides access to input actions defined in input action map "VideoPlayerControl".
    /// </summary>
    public struct VideoPlayerControlActions
    {
        private @VideoPlayerInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public VideoPlayerControlActions(@VideoPlayerInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "VideoPlayerControl/PlayPause".
        /// </summary>
        public InputAction @PlayPause => m_Wrapper.m_VideoPlayerControl_PlayPause;
        /// <summary>
        /// Provides access to the underlying input action "VideoPlayerControl/NextFrame".
        /// </summary>
        public InputAction @NextFrame => m_Wrapper.m_VideoPlayerControl_NextFrame;
        /// <summary>
        /// Provides access to the underlying input action "VideoPlayerControl/PreviousFrame".
        /// </summary>
        public InputAction @PreviousFrame => m_Wrapper.m_VideoPlayerControl_PreviousFrame;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_VideoPlayerControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="VideoPlayerControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(VideoPlayerControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="VideoPlayerControlActions" />
        public void AddCallbacks(IVideoPlayerControlActions instance)
        {
            if (instance == null || m_Wrapper.m_VideoPlayerControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VideoPlayerControlActionsCallbackInterfaces.Add(instance);
            @PlayPause.started += instance.OnPlayPause;
            @PlayPause.performed += instance.OnPlayPause;
            @PlayPause.canceled += instance.OnPlayPause;
            @NextFrame.started += instance.OnNextFrame;
            @NextFrame.performed += instance.OnNextFrame;
            @NextFrame.canceled += instance.OnNextFrame;
            @PreviousFrame.started += instance.OnPreviousFrame;
            @PreviousFrame.performed += instance.OnPreviousFrame;
            @PreviousFrame.canceled += instance.OnPreviousFrame;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="VideoPlayerControlActions" />
        private void UnregisterCallbacks(IVideoPlayerControlActions instance)
        {
            @PlayPause.started -= instance.OnPlayPause;
            @PlayPause.performed -= instance.OnPlayPause;
            @PlayPause.canceled -= instance.OnPlayPause;
            @NextFrame.started -= instance.OnNextFrame;
            @NextFrame.performed -= instance.OnNextFrame;
            @NextFrame.canceled -= instance.OnNextFrame;
            @PreviousFrame.started -= instance.OnPreviousFrame;
            @PreviousFrame.performed -= instance.OnPreviousFrame;
            @PreviousFrame.canceled -= instance.OnPreviousFrame;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="VideoPlayerControlActions.UnregisterCallbacks(IVideoPlayerControlActions)" />.
        /// </summary>
        /// <seealso cref="VideoPlayerControlActions.UnregisterCallbacks(IVideoPlayerControlActions)" />
        public void RemoveCallbacks(IVideoPlayerControlActions instance)
        {
            if (m_Wrapper.m_VideoPlayerControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="VideoPlayerControlActions.AddCallbacks(IVideoPlayerControlActions)" />
        /// <seealso cref="VideoPlayerControlActions.RemoveCallbacks(IVideoPlayerControlActions)" />
        /// <seealso cref="VideoPlayerControlActions.UnregisterCallbacks(IVideoPlayerControlActions)" />
        public void SetCallbacks(IVideoPlayerControlActions instance)
        {
            foreach (var item in m_Wrapper.m_VideoPlayerControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VideoPlayerControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="VideoPlayerControlActions" /> instance referencing this action map.
    /// </summary>
    public VideoPlayerControlActions @VideoPlayerControl => new VideoPlayerControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "VideoPlayerControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="VideoPlayerControlActions.AddCallbacks(IVideoPlayerControlActions)" />
    /// <seealso cref="VideoPlayerControlActions.RemoveCallbacks(IVideoPlayerControlActions)" />
    public interface IVideoPlayerControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "PlayPause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlayPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextFrame" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextFrame(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PreviousFrame" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPreviousFrame(InputAction.CallbackContext context);
    }
}
